### ISSUE TITLE
[Midterm]

### ISSUE THREAD

**Issue by akuznetsova** [akuznetsova/spf-2024#12]
#### Description:  
At the halfway point, we are wrapping up the star-formation part of the course, going from Galactic to planetary scales -- an immense dynamic range! The goal of the midterm is to try and put it all in context, applying the physics we've being talking about across the course to observational data across a range of relevant scales. Since there's a lot of ground to cover, we're going to divide up the contributions amongst the class, with everyone taking on a portion of the content. (A mini-seminar series of sorts).
The topic list below is grouped by spatial scale and/or tracer and/or type of study, but there is naturally going to be some overlap. This is where you might find it helpful to work together with people on similar topics to build up a foundational understanding and then branch out to your sub-topics. 

We'll be using google slides to create a single class presentation, so individual contributions will need to function as a cohesive part of the whole. There will be time in class on Monday March 25th for the class to workshop content, ask for feedback, and figure out how to bring your components together. I would recommend having *at least* a structured outline of your talking points ready so that everyone can use their time efficiently. At the conclusion of the midterm, as part of the grade, I'll be asking everyone to submit a "peer review" google form. (This is in the spirit of giving credit to your colleagues for their insightful contributions, any extra leg work they put in, or make visible other ways in which they supported the project at large. I will only be using peer review to see if I should **give** people points.)

#### Presentation Guidelines
**[Presentation Google Slide Link](https://docs.google.com/presentation/d/1-x_UGxyEHhJ_FP8DM4Wo5ya6meIE37wVc_X-ZEiy2zM/edit?usp=sharing)**  
Your presentation should discuss at least one observational study of that topic from the literature -- breaking down the relevant physics, emission mechanisms, sources of uncertainty, etc. Your discussion of that study should communicate a general conceptual picture of how the topic is studied and what the relevant observational tracers are and how they relate to the physics at play. You should be prepared to field questions relevant to the course material in a brief 2-3 min Q/A. (1 Q from me + any from your colleagues). 
In practice, this means you'll want to approach this as if you're conducting a literature review, reading multiple sources to build your understanding of the topic, and then choosing a specific study to showcase the basic concepts. In lieu of asking you to write a lit review, I will be asking you to turn in a bibliography of the papers you used. Review papers are a good place to start looking to build your understanding and look for more sources. 

Protostars and Planets is a book of review papers from a field-wide conference series on star and planet formation held every seven years, the last one was just last year! You can find the [listed review chapters here](https://www.aspbooks.org/a/volumes/table_of_contents/?book_id=620). Note: You don't need to buy the book, you can click on any of the chapters to view the articles themselves for free (they are also all on arxiv). 

#### Graded components
1. 5 min presentation of slide contributions to class presentation ( + 2-3 min Q/A per person) 
2. bibliography of sources used (additional menu points will be given for annotated bibliography submissions)
3. peer review  (google form)
4. by March 27th: set up a meeting time with me for mid-semester check-in

#### Topic list:
* Molecular clouds  ➡️ Manny
* HII regions ➡️  Vanessa
* Star forming regions: gas  ➡️ Angeli
* Star forming regions: population behavior of YSOs/stars  ➡️ Ryan
* Pre/Proto-Stellar Cores: dust  ➡️ Olga
* Pre/Proto-Stellar Cores: gas
* Pre/Proto-Stellar Cores: magnetic fields  ➡️ Theo
* YSOs: detection + characterization  ➡️ Austen
* YSOs: accretion  ➡️ Justin
* YSOs: age dating  ➡️ Andrew
* YSOs/Disks: Jets/Outflows/Herbig-Haro Objects ➡️  Austin
* Disks (Class 0/I) ➡️ Shirin
* Disks (Class II) ➡️  Rosario

#### Action Item:
Need to have a topic selected no later than March 18th - first come first serve. (Can post here in the thread or contact me)

**Comment by nirihs** [comment]
Hi Aleksandra! Can I use _Hydro-, Magnetohydro-, and Dust-Gas Dynamics of Protoplanetary Disks_ (**Lesur+2022**) from PPVII to start as the topic of my project? I think I'll be crafting a project around figure 6 in the chapter, discussing what processes dominate what regions of a **_class 0/I_** disk.

**Comment by rothermichaustin** [comment]
I would like to select the topic - YSOs/Disks: Jets/Outflows/Herbig-Haro Objects

**Comment by vambrown** [comment]
I'd like to take _HII regions_.

**Comment by JustinBopp** [comment]
I would like to do YSOs: accretion

**Comment by aye-kuma** [comment]
I would like to work on Pre/Proto-Stellar Cores: magnetic fields

**Comment by MERH23** [comment]
I would like my section to be on Molecular clouds.

**Comment by aust427** [comment]
I would to work on YSOs: detection + characterization for the midterm.

**Comment by angelis21** [comment]
I would like to do: Star forming regions: gas

**Comment by RosarioCecilio** [comment]
I'd like to do Disks (Class 0/I)

**Comment by andrew-ayala** [comment]
I will do YSO's: Age Dating

**Comment by OlggiWan** [comment]
I'd like Pre/Proto-Stellar Cores, please!
