### ISSUE TITLE
[Class recap] [w2]

### ISSUE THREAD

**Issue by akuznetsova** [akuznetsova/spf-2024#5]
Instructions:
Make a copy of the [recap template](https://github.com/akuznetsova/spf-2024/blob/main/templates/%5BTEMPLATE%5D-recap.md) file in the directory for week 2, replacing the [TEMPLATE] in the title with the date in Mon.-Day format (ex: Jan-31-recap.md).
(You can also just go into Edit mode, copy the contents and paste them into a new markdown file
you make in the corresponding directory).
Remove all the template text and fill in with your recap.
When you're ready, submit with the commit title:
CLASS RECAP-[NAME] and comment below with a link to the file.

This week:
+ recap for 2/5 (due before class 2/7)
+ recap for 2/7 (due before class 2/14)

**Comment by vambrown** [comment]
[Recap 2/5](https://github.com/akuznetsova/spf-2024/blob/main/w2/Feb-5-recap.md)

commit e69c768042ff9a67fd327b4424407a3566c095fe

**Comment by akuznetsova** [comment]
@vambrown

reviewed: 1/1

**Comment by akuznetsova** [comment]
@MERH23 
[recap 2/7](https://github.com/akuznetsova/spf-2024/blob/main/w2/Feb_7_recap.md)
commit 51c26578f6b3833fb1c9c0119c569f8f094c7c14

reviewed 1/1
